create table bookings
(
    id             bigint generated by default as identity
        constraint bookings_pk
            primary key,
    resource_id    bigint                         not null
        constraint "fk-bookings-resource_id"
            references resource,
    requested_by   bigint                         not null
        constraint fk_bookings_requested_by
            references users,
    bid_amount     double precision default 0     not null,
    booking_status int              default 1     not null,
    start_time     timestamp                      not null,
    end_time       timestamp                      not null,
    deleted        boolean          default false not null
);

create index "bookings__resource_id-requested"
    on bookings (resource_id asc, requested_by asc, booking_status asc, start_time desc);

