create table users
(
    id             bigint generated by default as identity
        constraint users_pk
            primary key,
    name           varchar(50)           not null,
    legal_name     varchar(60)           not null,
    email          varchar(60)           not null,
    mobile         varchar(20)           not null,
    user_state  int default 0,
    password_hash VARCHAR(255) NOT NULL,
    email_verified boolean default false not null,
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE,
    profile_picture_url VARCHAR(255),
    date_of_birth DATE,
    gender VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    google_id VARCHAR(255),
    phone_verified BOOLEAN DEFAULT FALSE,
    auth_provider VARCHAR(50)
);

create index users__index_email_id
    on users (email);

create index users__index_mobile
    on users (mobile);

alter table users
    add constraint users_pk_2
        unique (email);

alter table users
    add constraint users_pk_3
        unique (mobile);

