create table refresh_tokens
(
    id         bigint generated by default as identity
        constraint refresh_tokens_pk
            primary key,
    user_id    bigint       not null
        constraint refresh_tokens___fk_use_id
            references users,
    token      varchar(255) not null
        constraint refresh_tokens_pk_2
            unique,
    expires_at timestamp    not null,
    created_at timestamp    not null
);

create index refresh_tokens__index_user_id
    on refresh_tokens (user_id);