create table resource_category
(
    id          int generated by default as identity
        constraint resource_category_pk
            primary key,
    name        varchar(60)  not null,
    description varchar(255) not null
);

