create table resource
(
    id             bigint generated by default as identity
        constraint resource_pk
            primary key,
    name           varchar(100)      not null,
    description    text,
    category_id    integer
        constraint resource___fk_category_id
            references resource_category (id),
    owned_by       bigint            not null
        constraint resource___fk_owned_by
            references users,
    current_status integer default 1 not null,
    value          float   default 0,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
    created_by bigint not null constraint resource___fk_created_by
        references users,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
    updated_by bigint not null constraint resource___fk_updated_by
        references users
);

comment on column resource.value is 'Value per hour';

