create table user_addresses
(
    id             bigint generated by default as identity
        constraint user_addresses_pk
            primary key,
    user_id        bigint                              not null,
    address_type   integer                             not null,
    city           varchar(60)                         not null,
    district       varchar(60)                         not null,
    pincode        varchar(20)                         not null,
    state          varchar(60)                         not null,
    country        varchar(60)                         not null,
    address_line_1 varchar(60),
    address_line_2 varchar(60),
    deleted        boolean   default false,
    created_at     timestamp default CURRENT_TIMESTAMP not null,
    updated_at     timestamp default CURRENT_TIMESTAMP not null
);

