create table resource_images
(
    id          bigint generated by default as identity
        constraint resource_images_pk
            primary key,
    resource_id bigint                              not null
        constraint resource_images___fk_resource_id
            references resource (id),
    image_url   varchar(100)                        not null,
    is_primary  boolean   default false             not null,
    deleted     boolean   default false,
    created_at  timestamp default CURRENT_TIMESTAMP not null,
    updated_at  timestamp default CURRENT_TIMESTAMP not null,
    created_by  bigint                              not null
        constraint resource_images___fk_created_by
            references users,
    updated_by  bigint
        constraint resource_images___fk_updated_by
            references users
);

